### ISSUE TITLE
community-detection-demo.ipynb mentions package graph_viz, but not found in the repository

### ISSUE THREAD

**Issue by harold-i-kimmey** [qci-github/qatalyst-examples#1]
The repository includes a helpers.py file and it looks like graph_viz would be included in there, but is not included.

Could the package or details about the package be included in the repository (README, requirements.txt or helpers.py).

Thank you!

Harold Kimmey
216-357-9227
harold_i_kimmey@progressive.com

**Comment by qci-github** [comment]
Changing the reference to helpers instead of graph_viz, an old and busted module. This fix has been merged to main.
